### ISSUE TITLE
Language server is not started properly

### ISSUE THREAD

**Issue by Y-jiji** [plt-amy/vscode-agda#1]
Here is the version of agda. 
![image](https://github.com/plt-amy/vscode-agda/assets/71013200/3ae6ade6-abb7-4a23-844c-50f9c2d609b0)
Here is the error emitted by this codebase. 
![image](https://github.com/plt-amy/vscode-agda/assets/71013200/6757e224-0105-4032-9f8f-1d592f96a0a0)
Peeking into this codebase a little, I found an `--lsp` argument is passed to `agda` executable, but it seems `agda` executable doesn't accept this argument. 
![image](https://github.com/plt-amy/vscode-agda/assets/71013200/758d6e84-59e2-4723-ab57-fb30014a3b93)
Please help me make this work, great thanks!

**Comment by SquidDev** [comment]
Hi! I'm afraid plugin is still in-development, and requires a fork of Agda with built-in LSP support. For now I'd recommend using the https://marketplace.visualstudio.com/items?itemName=banacorn.agda-mode plugin.
